config/routes.rb
Html5WebsiteBuilder::Application.routes.draw do

  scope "/build" do
  
    resources :offerpages do
      member do
        get 'publish'
      end
    end

    resources :articles do
      member do
        get 'publish'
      end
    end
  
    resources :settings
    
    root :to => "home#index"
  
  end

  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'

  match '/signin' => 'sessions#new', :as => :signin

  match '/signout' => 'sessions#destroy', :as => :signout

  match '/auth/failure' => 'sessions#failure'

end

app/models/offerpage.rb
class Offerpage
  include Mongoid::Document
  field :title, :type => String
  field :filename, :type => String
  field :description, :type => String
  field :keywords, :type => String
  field :headline, :type => String
  field :subhead, :type => String
  field :content_block1, :type => String
  field :content_block2, :type => String
  field :offer_block, :type => String
  field :testimonials, :type => String
  field :video, :type => String
  field :published, :type => Boolean
end

app/controllers/offerpages_controller.rb
class OfferpagesController < ApplicationController

  before_filter :get_settings, :only => [:publish, :index, :new, :destroy]

  def publish
    @offerpage = Offerpage.find(params[:id])
    @permalink = "http://#{@settings.domain}/#{@settings.offerpages_directory}/#{@offerpage.filename}.html"
    offerpage_page = render_to_string(:template => "offerpages/template.html.haml", :layout => false )
    FileUtils.makedirs(@file_path) unless File.exists?(@file_path)
    File.open("#{@file_path + @offerpage.filename}.html", 'w') {|f| f.write(offerpage_page) }
    @offerpage.update_attribute(:published, true)
    respond_to do |format|
      format.html { redirect_to offerpages_path, notice: "Built a webpage for the offer page \"#{@offerpage.title}\"" }
    end

  end
  
  def index
    @offerpages = Offerpage.all
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @offerpage = Offerpage.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @offerpage = Offerpage.new
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @offerpage = Offerpage.find(params[:id])
  end

  def create
    @offerpage = Offerpage.new(params[:offerpage])
    if params[:format] == 'html'
      p1 = HTMLToTextileParser.new
      p2 = HTMLToTextileParser.new
      p3 = HTMLToTextileParser.new
      p4 = HTMLToTextileParser.new
      p1.feed(params[:offerpage][:content_block1])
      @offerpage.content_block1 = p1.to_textile
      p2.feed(params[:offerpage][:content_block2])
      @offerpage.content_block2 = p2.to_textile
      p3.feed(params[:offerpage][:offer_block])
      @offerpage.offer_block = p3.to_textile
      p4.feed(params[:offerpage][:testimonials])
      @offerpage.testimonials = p4.to_textile
    end
    respond_to do |format|
      if @offerpage.save
        format.html { redirect_to offerpages_path, notice: 'Offerpage was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @offerpage = Offerpage.find(params[:id])
    respond_to do |format|
      if @offerpage.update_attributes(params[:offerpage])
        format.html { redirect_to offerpages_path, notice: 'Offerpage was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @offerpage = Offerpage.find(params[:id])
    @offerpage.destroy
    @settings = Setting.first
    FileUtils.remove_file("#{@file_path + @offerpage.filename}.html", force = true)
    respond_to do |format|
      format.html { redirect_to offerpages_url }
    end
  end
  
  protected    
    def get_settings
      @settings = Setting.first
      @docroot_path = "#{Rails.root}/public/"
      @file_path = "#{@docroot_path}#{@settings.offerpages_directory}/"
      @url_path = "/#{@settings.offerpages_directory}/"
    end
end

app/helpers/offerpages_helper.rb
module OfferpagesHelper
end

app/views/offerpages/_form.html.haml
= form_for @offerpage do |f|
  -if @offerpage.errors.any?
    #error_explanation
      %h2= "#{pluralize(@offerpage.errors.count, "error")} prohibited this offerpage from being saved:"
      %ul
        - @offerpage.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :filename
    = f.text_field :filename
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :keywords
    = f.text_area :keywords
  .field
    = f.label :headline
    = f.text_area :headline
  .field
    = f.label :subhead
    = f.text_area :subhead
  .field
    = radio_button_tag(:format, "textile")
    = label_tag(:format_textile, "Textile")
    = radio_button_tag(:format, "html")
    = label_tag(:format_html, "Convert HTML to Textile")
  .field
    = f.label :content_block1
    = f.text_area :content_block1
  .field
    = f.label :content_block2
    = f.text_area :content_block2
  .field
    = f.label :offer_block
    = f.text_area :offer_block
  .field
    = f.label :testimonials
    = f.text_area :testimonials
  .field
    = f.label :video
    = f.text_area :video
  .actions
    = f.submit 'Save'

app/views/offerpages/edit.html.haml
%h1 Editing offerpage

= render 'form'

= link_to 'Show', @offerpage
\|
= link_to 'Back', offerpages_path

app/views/offerpages/index.html.haml
%h2 Offer Pages

%table
  - @offerpages.each do |offerpage|
    %tr
      %td.three.columns= link_to offerpage.title, offerpage
      %td.two.columns= link_to 'Edit', edit_offerpage_path(offerpage)
      %td.two.columns= link_to 'Publish', publish_offerpage_path(offerpage)
      %td.two.columns= link_to 'Remove', offerpage, :confirm => 'Are you sure?', :method => :delete
      %td.two.columns
        - if offerpage.published
          = link_to "#{@url_path + offerpage.filename}.html", "#{@url_path + offerpage.filename}.html"

%br

= link_to 'New Offerpage', new_offerpage_path

app/views/offerpages/new.html.haml
%h1 New offerpage

= render 'form'

= link_to 'Back', offerpages_path

app/views/offerpages/publish.html.haml
%p
  %b Title:
  = @offerpage.title
%p
  %b View it here:
  = link_to "#{@url_path + @offerpage.filename}.html", "#{@url_path + @offerpage.filename}.html"

app/views/offerpages/show.html.haml
%p
  %b Title:
  = @offerpage.title
%p
  %b Filename:
  = @offerpage.filename
%p
  %b Description:
  = @offerpage.description
%p
  %b Keywords:
  = @offerpage.keywords
%p
  %b Headline:
  = @offerpage.headline
%p
  %b Subhead:
  = @offerpage.subhead
%p
  %b Content Block 1:
  = @offerpage.content_block1
%p
  %b Content Block 2:
  = @offerpage.content_block2
%p
  %b Offer Block:
  = @offerpage.offer_block
%p
  %b Testimonials:
  = @offerpage.testimonials
%p
  %b Video:
  = @offerpage.video
  
= link_to 'Edit', edit_offerpage_path(@offerpage)
\|
= link_to 'Back', offerpages_path

app/views/offerpages/template.html.haml
- html_tag class: 'no-js' do
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %meta{:name=>'description', :content=>"#{@offerpage.description}"}
    %meta{:name=>'keywords', :content=>"#{@offerpage.keywords}"}
    -# meta tags for the Open Graph protocol for Facebook
    %meta{:property => "og:title", :content => "#{@offerpage.title}"}
    %meta{:property => "og:type", :content => "product"}
    %meta{:property => "og:url", :content => "#{@permalink}"}
    %meta{:property => "og:image", :content => ""}
    %meta{:property => "og:description", :content => "#{@offerpage.description}"}
    %meta{:property => "og:site_name", :content => "#{@settings.site_name}"}
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
    %title
      = @offerpage.title
    %body{:class => params[:controller]}
      .container
        .logo.sixteen.columns
        %br.clear
        .row
          .recommend.two.columns.alpha
            .plusone
              %g:plusone{:size => "tall"}
            .tweet
              %a.twitter-share-button{"data-count" => "none", 
                "data-via" => "#{@settings.twitter_account}", :href => "http://twitter.com/share"}
          .twelve.columns.box.clearfix.omega
            %section
              - unless @offerpage.video.blank?
                .video
                  %script{:type => "text/javascript",
                          :src  => "#{@offerpage.video}"}
                  %p Press Play to Watch This Video
              #fb-root
                %fb:like{:action => "recommend", :send => "true", :show_faces => "false", :width => "450"}
              %header
                %hgroup
                  %h1
                    :textile
                      #{@offerpage.headline}
                  %h2
                    :textile
                      #{@offerpage.subhead}
              :textile
                #{@offerpage.content_block1}
              %section
                - if @offerpage.testimonials
                  %aside
                    %section
                      :textile
                        #{@offerpage.testimonials}
                :textile
                  #{@offerpage.content_block2}
            %br.clear
            %section
              :textile
                #{@offerpage.offer_block}
        %br.clear
        %hr/
        %footer.twelve.columns
      -# Javascript for Facebook, Twitter, and Google+ sharing
      %script{:type => "text/javascript",
                  :src  => "http://connect.facebook.net/en_US/all.js#appId=176448065752391&xfbml=1"}
      %script{:type => "text/javascript",
                  :src  => "http://platform.twitter.com/widgets.js"}
      %script{:type => "text/javascript",
                  :src  => "https://apis.google.com/js/plusone.js"}