config/routes.rb
Html5WebsiteBuilder::Application.routes.draw do

  scope "/build" do
  
    resources :offerpages do
      member do
        get 'publish'
      end
    end

    resources :articles do
      member do
        get 'publish'
      end
    end
  
    resources :settings
    
    root :to => "home#index"
  
  end

  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'

  match '/signin' => 'sessions#new', :as => :signin

  match '/signout' => 'sessions#destroy', :as => :signout

  match '/auth/failure' => 'sessions#failure'

end

app/models/article.rb
class Article
  include Mongoid::Document
  field :title, :type => String
  field :filename, :type => String
  field :description, :type => String
  field :keywords, :type => String
  field :headline, :type => String
  field :subhead, :type => String
  field :content, :type => String
  field :sidebar, :type => String
  field :published, :type => Boolean
  # key :filename
  field :related_items, :type => Array
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :get_settings, :only => [:publish, :index, :new, :destroy]

  def publish
    # create an article page
    @article = Article.find(params[:id])
    @related_items = Hash.new
    if @article.related_items
      @article.related_items.each do |id|
        item = Article.find(id)
        @related_items[item.title] = "#{item.filename}.html"
      end
    end
    @permalink = "http://#{@settings.domain}/#{@settings.articles_directory}/#{@article.filename}.html"
    @content = RedCloth.new(@article.content).to_html.html_safe
    @sidebar = RedCloth.new(@article.sidebar).to_html.html_safe if @article.sidebar
    article_page = render_to_string(:template => "articles/template.html.haml", :layout => false )
    FileUtils.makedirs(@file_path) unless File.exists?(@file_path)
    File.open("#{@file_path + @article.filename}.html", 'w') {|f| f.write(article_page) }
    @article.update_attribute(:published, true)
    # create (or recreate) the welcome page
    @articles = Article.where(published: true)
    @welcome_sidebar = RedCloth.new(@settings.sidebar).to_html.html_safe if @settings.sidebar
    welcome_page = render_to_string(:template => "welcome/template.html.haml", :layout => false )
    File.open("#{@docroot_path}index.html", 'w') {|f| f.write(welcome_page) }
    respond_to do |format|
      format.html { redirect_to articles_path, notice: "Built a webpage for the article \"#{@article.title}\"" }
    end

  end

  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @article = Article.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @article = Article.new
    @articles = Article.all
    @article.related_items = []
    @article.sidebar = @settings.sidebar if @settings.sidebar
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @article = Article.find(params[:id])
    @articles = Article.all
  end

  def create
    @article = Article.new(params[:article])
    if params[:format] == 'html'
      p1 = HTMLToTextileParser.new
      p2 = HTMLToTextileParser.new
      p1.feed(params[:offerpage][:content])
      @offerpage.content = p1.to_textile
      p2.feed(params[:offerpage][:sidebar])
      @offerpage.sidebar = p2.to_textile
    end
    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_path, notice: 'Article was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @article = Article.find(params[:id])
    params[:article][:related_items] ||= []
    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to articles_path, notice: 'Article was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    @settings = Setting.first
    FileUtils.remove_file("#{@file_path + @article.filename}.html", force = true)
    respond_to do |format|
      format.html { redirect_to articles_url }
    end
  end
  
  protected    
    def get_settings
      @settings = Setting.first
      @docroot_path = "#{Rails.root}/public/"
      @file_path = "#{@docroot_path}#{@settings.articles_directory}/"
      @url_path = "/#{@settings.articles_directory}/"
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  -if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :filename
    = f.text_field :filename
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :keywords
    = f.text_field :keywords
  .field
    = f.label :headline
    = f.text_field :headline
  .field
    = f.label :subhead
    = f.text_field :subhead
  .field
    = radio_button_tag(:format, "textile")
    = label_tag(:format_textile, "Textile")
    = radio_button_tag(:format, "html")
    = label_tag(:format_html, "Convert HTML to Textile")    
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :sidebar
    = f.text_area :sidebar
  .field
    = f.label :related_item
  = f.fields_for :related_item do |b|
    - Article.all.each do |item|
      %div
        = check_box_tag "article[related_items][]", item.id, 
          (@article.related_items.include?(item._id.to_s) if @article.related_items)
        = item.title
  .actions
    = f.submit 'Save'

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h2 Articles

%table
  - @articles.each do |article|
    %tr
      %td.three.columns= link_to article.title, article
      %td.two.columns= link_to 'Edit', edit_article_path(article)
      %td.two.columns= link_to 'Publish', publish_article_path(article)
      %td.two.columns= link_to 'Remove', article, :confirm => 'Are you sure?', :method => :delete
      %td.two.columns
        - if article.published
          = link_to "#{@url_path + article.filename}.html", "#{@url_path + article.filename}.html"

%br

= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/publish.html.haml
%p
  %b Title:
  = @article.title
%p
  %b View it here:
  = link_to "#{@url_path + @article.filename}.html", "#{@url_path + @article.filename}.html"

app/views/articles/show.html.haml
%p
  %b Title:
  = @article.title
%p
  %b Filename:
  = @article.filename
%p
  %b Description:
  = @article.description
%p
  %b Keywords:
  = @article.keywords
%p
  %b Headline:
  = @article.headline
%p
  %b Subhead:
  = @article.subhead
%p
  %b Content:
  = @article.content

%p
  %b Article sidebar:
  = @article.sidebar
    
%p
  %b Related Articles:
  - if @article.related_items
    - @article.related_items.each do |item|
      %br
      = item

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path

app/views/articles/template.html.haml
- html_tag class: 'no-js' do
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %meta{:name=>'description', :content=>"#{@article.description}"}
    %meta{:name=>'keywords', :content=>"#{@article.keywords}"}
    -# meta tags for the Open Graph protocol for Facebook
    %meta{:property => "og:title", :content => "#{@article.title}"}
    %meta{:property => "og:type", :content => "article"}
    %meta{:property => "og:url", :content => "#{@permalink}"}
    %meta{:property => "og:image", :content => ""}
    %meta{:property => "og:description", :content => "#{@article.description}"}
    %meta{:property => "og:site_name", :content => "#{@settings.site_name}"}
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
    %title
      = @article.title
    %body{:class => params[:controller]}
      .container
        .logo.sixteen.columns
          .sitename
            = link_to @settings.site_name, '/index.html'
          .tagline
            = @settings.site_tagline
        %hr/
        %article.twelve.columns
          %header
            %hgroup
              %h1
                = @article.headline
              %h2
                = @article.subhead
          = @content
          #fb-root
            %fb:like{:action => "recommend", :send => "true", :show_faces => "false", :width => "450"}
        %aside.four.columns
          %section
            %h1
              Recommend This Article
            %ul
              %li
                %g:plusone{:count => "medium", :size => "small"}
              %li
                %a.twitter-share-button{"data-count" => "none", 
                  "data-via" => "#{@settings.twitter_account}", :href => "http://twitter.com/share"}
          %section
            %h1
              Related Articles
            %ul
              - if @related_items.empty?
                %li
                  none
              - else
                - @related_items.each do |title, link|
                  %li
                    = link_to title, link
          - unless @sidebar.blank?
            %section
              %hr
              = @sidebar
              %hr
        %footer.sixteen.columns
          %hr/
      -# Javascript for Facebook, Twitter, and Google+ sharing
      %script{:type => "text/javascript",
                  :src  => "http://connect.facebook.net/en_US/all.js#appId=176448065752391&xfbml=1"}
      %script{:type => "text/javascript",
                  :src  => "http://platform.twitter.com/widgets.js"}
      %script{:type => "text/javascript",
                  :src  => "https://apis.google.com/js/plusone.js"}