config/routes.rb
Html5WebsiteBuilder::Application.routes.draw do

  scope "/build" do
  
    resources :offerpages do
      member do
        get 'publish'
      end
    end

    resources :articles do
      member do
        get 'publish'
      end
    end
  
    resources :settings
    
    root :to => "home#index"
  
  end

  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'

  match '/signin' => 'sessions#new', :as => :signin

  match '/signout' => 'sessions#destroy', :as => :signout

  match '/auth/failure' => 'sessions#failure'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def index
    @users = User.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.one-third.column
  %h3 Build a Website
  %p Skeleton is a small collection of well-organized CSS & JS files that can help you rapidly develop sites that look beautiful at any size, be it a 17" laptop screen or an iPhone. It's based on a responsive grid, but also provides very basic CSS for typography, buttons, tabs, forms and media queries. Go ahead, resize this super basic page to see the grid in action.
.one-third.column
  %h3 Get Started
  %p Skeleton is built on three core principles:
  %ul.square
    %li
      %strong
        =link_to "Pick Your Keywords:", settings_path
      \ Provide basic information about your site.
    %li
      %strong
        =link_to "Create an Offer:", offerpages_path
      \ Add a page to sell a product or capture an email address.
    %li
      %strong
        =link_to "Add Articles:", articles_path
      \ Create a bridge between popular searches and your offer.
    %li
      %strong Publish to the Web:
      \ #{link_to "View your site", "/index.html"},
      \ then deploy to a free web host.
.one-third.column
  %h3 Docs & Support
  %p blah blah