config/routes.rb
Html5WebsiteBuilder::Application.routes.draw do

  scope "/build" do
  
    resources :offerpages do
      member do
        get 'publish'
      end
    end

    resources :articles do
      member do
        get 'publish'
      end
    end
  
    resources :settings
    
    root :to => "home#index"
  
  end

  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'

  match '/signin' => 'sessions#new', :as => :signin

  match '/signout' => 'sessions#destroy', :as => :signout

  match '/auth/failure' => 'sessions#failure'

end

app/models/setting.rb
class Setting
  include Mongoid::Document
  field :site_name, :type => String
  field :site_title, :type => String
  field :site_tagline, :type => String
  field :site_description, :type => String
  field :site_keywords, :type => String
  field :twitter_account, :type => String
  field :domain, :type => String
  field :articles_directory, :type => String
  field :offerpages_directory, :type => String
  field :sidebar, :type => String
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
    @setting = Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/new
  # GET /settings/new.json
  def new
    @setting = Setting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(params[:setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render json: @setting, status: :created, location: @setting }
      else
        format.html { render action: "new" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:id])

    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.haml
= form_for @setting do |f|
  -if @setting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@setting.errors.count, "error")} prohibited this setting from being saved:"
      %ul
        - @setting.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :site_name
    = f.text_field :site_name
  .field
    = f.label :site_title
    = f.text_field :site_title
  .field
    = f.label :site_tagline
    = f.text_field :site_tagline
  .field
    = f.label :site_description
    = f.text_field :site_description
  .field
    = f.label :site_keywords
    = f.text_field :site_keywords
  .field
    = f.label :twitter_account
    = f.text_field :twitter_account
  .field
    = f.label :domain
    = f.text_field :domain
  .field
    = f.label :articles_directory
    = f.text_field :articles_directory
  .field
    = f.label :offerpages_directory
    = f.text_field :offerpages_directory
  .field
    = f.label :sidebar
    = f.text_area :sidebar
  .actions
    = f.submit 'Save'

app/views/settings/edit.html.haml
%h1 Editing setting

= render 'form'

= link_to 'Show', @setting
\|
= link_to 'Back', settings_path

app/views/settings/index.html.haml
%h1 Listing settings

%table
  %tr
    %th Articles path
    %th
    %th
    %th

  - @settings.each do |setting|
    %tr
      %td= setting.articles_directory
      %td= link_to 'Show', setting
      %td= link_to 'Edit', edit_setting_path(setting)
      %td= link_to 'Destroy', setting, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Setting', new_setting_path

app/views/settings/new.html.haml
%h1 New setting

= render 'form'

= link_to 'Back', settings_path

app/views/settings/show.html.haml
%p
  %b Site Name:
  = @setting.site_name
%p
  %b Domain:
  = @setting.domain
%p
  %b Site title:
  = @setting.site_title
%p
  %b Tagline:
  = @setting.site_tagline
%p
  %b Site description:
  = @setting.site_description
%p
  %b Site keywords:
  = @setting.site_keywords
%p
  %b Articles directory:
  = @setting.articles_directory
%p
  %b Offer Pages directory:
  = @setting.offerpages_directory
%p
  %b Twitter account:
  = @setting.twitter_account
%p
  %b Article sidebar:
  = @setting.sidebar
    
= link_to 'Edit', edit_setting_path(@setting)
\|
= link_to 'Back', settings_path